---
- name: Install Jenkins
  hosts: jenkins
  remote_user: '{{ansible_user}}'
  become: true
  roles:
    - { role: jenkins-ubuntu, when: ansible_distribution == 'Ubuntu' }
    - { role: jenkins-centos, when: ansible_distribution == 'Centos' }